metasrht/blueprints/billing.py
import requests
import stripe
from datetime import datetime, timedelta
from flask import Blueprint, render_template, request, redirect
from flask import url_for, abort, Response
from metasrht.audit import audit_log
from metasrht.billing import charge_user
from metasrht.types import User, UserType, PaymentInterval, Invoice
from metasrht.webhooks import deliver_profile_update
from sqlalchemy import and_
from srht.config import cfg, get_origin
from srht.crypto import encrypt_request_authorization
from srht.database import db
from srht.flask import session
from srht.oauth import current_user, loginrequired, freshen_user
from srht.validation import Validation

billing = Blueprint('billing', __name__)
onboarding_redirect = cfg("meta.sr.ht::settings", "onboarding-redirect")

@billing.route("/billing")
@loginrequired
def billing_GET():
    message = session.get("message")
    if message:
        del session["message"]
    customer = None
    if current_user.stripe_customer:
        customer = stripe.Customer.retrieve(current_user.stripe_customer)
    total_users = (User.query
            .filter(User.user_type != UserType.unconfirmed)
            .filter(User.user_type != UserType.suspended)).count()
    total_paid = (User.query
            .filter(User.payment_cents != 0)
            .filter(User.user_type == UserType.active_paying)).count()
    invoices = (Invoice.query
            .filter(Invoice.user_id == current_user.id)
            .order_by(Invoice.created.desc())).all()
    return render_template("billing.html", message=message, customer=customer,
            total_users=total_users, total_paid=total_paid,
            paid_pct="{:.2f}".format(total_paid / total_users * 100),
            invoices=invoices)

@billing.route("/billing/initial")
@loginrequired
def billing_initial_GET():
    total_users = (User.query
            .filter(User.user_type != UserType.unconfirmed)
            .filter(User.user_type != UserType.suspended)).count()
    total_paid = (User.query
            .filter(User.payment_cents != 0)
            .filter(User.user_type == UserType.active_paying)).count()
    return_to = request.args.get("return_to")
    if return_to:
        session["return_to"] = return_to
    return render_template("billing-initial.html",
            total_users=total_users, total_paid=total_paid,
            paid_pct="{:.2f}".format(total_paid / total_users * 100))

@billing.route("/billing/initial", methods=["POST"])
@loginrequired
def billing_initial_POST():
    valid = Validation(request)
    amount = valid.require("amount")
    amount = int(amount)
    plan = valid.require("plan")
    valid.expect(not amount or amount > 0, "Expected amount >0")
    if not valid.ok:
        return "Invalid form submission", 400
    current_user.payment_cents = amount
    db.session.commit()
    if current_user.stripe_customer:
        return redirect(url_for("billing.billing_chperiod_GET"))
    return redirect(url_for("billing.new_payment_GET"))

@billing.route("/billing/change-period")
@loginrequired
def billing_chperiod_GET():
    if not current_user.stripe_customer:
        return redirect(url_for("billing.new_payment_GET"))
    return render_template("billing-change-period.html")

@billing.route("/billing/change-period", methods=["POST"])
def billing_chperiod_POST():
    if not current_user.stripe_customer:
        return redirect(url_for("billing.new_payment_GET"))
    valid = Validation(request)
    term = valid.require("term")
    audit_log("billing", "Payment term changed")
    current_user.payment_interval = PaymentInterval(term)
    success, details = charge_user(current_user)
    db.session.commit()
    freshen_user()
    deliver_profile_update(current_user)

    return_to = session.pop("return_to", None)
    if return_to:
        return redirect(return_to)
    session["message"] = "Your subscription has been updated."
    return redirect(url_for("billing.billing_GET"))

@billing.route("/billing/new-payment")
@loginrequired
def new_payment_GET():
    if not current_user.payment_cents:
        return redirect(url_for("billing.billing_initial_GET"))
    return render_template("new-payment.html",
            amount=current_user.payment_cents)

@billing.route("/billing/new-payment", methods=["POST"])
@loginrequired
def new_payment_POST():
    valid = Validation(request)
    term = valid.require("term")
    token = valid.require("stripe-token")
    if not valid.ok:
        return "Invalid form submission", 400
    if not current_user.stripe_customer:
        new_customer = True
        try:
            customer = stripe.Customer.create(
                    description="~" + current_user.username,
                    email=current_user.email,
                    card=token)
            current_user.stripe_customer = customer.id
            current_user.payment_due = datetime.utcnow() + timedelta(minutes=-5)
        except stripe.error.CardError as e:
            details = e.json_body["error"]["message"]
            return render_template("new-payment.html",
                    amount=current_user.payment_cents, error=details)
    else:
        new_customer = False
        if current_user.user_type != UserType.active_paying:
            current_user.payment_due = datetime.utcnow() + timedelta(minutes=-5)
        try:
            customer = stripe.Customer.retrieve(current_user.stripe_customer)
            source = customer.sources.create(source=token)
            customer.default_source = source.stripe_id
            customer.save()
        except stripe.error.CardError as e:
            details = e.json_body["error"]["message"]
            return render_template("new-payment.html",
                    amount=current_user.payment_cents, error=details)
    audit_log("billing", "New payment method handed")
    current_user.payment_interval = PaymentInterval(term)
    success, details = charge_user(current_user)
    if not success:
        return render_template("new-payment.html",
                amount=current_user.payment_cents, error=details)
    db.session.commit()
    freshen_user()
    deliver_profile_update(current_user)

    return_to = session.pop("return_to", None)
    if return_to:
        return redirect(return_to)
    if new_customer:
        return redirect(url_for("billing.billing_complete"))
    session["message"] = "Your payment method was updated."
    return redirect(url_for("billing.billing_GET"))

@billing.route("/billing/remove-source/<source_id>", methods=["POST"])
@loginrequired
def payment_source_remove(source_id):
    try:
        stripe.Customer.delete_source(
                current_user.stripe_customer,
                source_id)
    except stripe.error.StripeError:
        abort(404)
    session["message"] = "Your payment method was removed successfully."
    return redirect(url_for("billing.billing_GET"))

@billing.route("/billing/set-default-source/<source_id>", methods=["POST"])
@loginrequired
def payment_source_make_default(source_id):
    try:
        stripe.Customer.modify(
                current_user.stripe_customer,
                default_source=source_id)
    except stripe.error.StripeError as ex:
        print(ex)
        abort(404)
    session["message"] = "Your payment method was updated successfully."
    return redirect(url_for("billing.billing_GET"))

@billing.route("/billing/complete")
@loginrequired
def billing_complete():
    return render_template("billing-complete.html",
            onboarding_redirect=onboarding_redirect)

@billing.route("/billing/cancel", methods=["POST"])
@loginrequired
def cancel_POST():
    current_user.payment_cents = 0
    db.session.commit()
    freshen_user()
    deliver_profile_update(current_user)
    audit_log("billing", "Plan cancelled (will not renew)")
    return redirect(url_for("billing.billing_GET"))

@billing.route("/billing/invoice/<int:invoice_id>")
@loginrequired
def invoice_GET(invoice_id):
    invoice = Invoice.query.filter(Invoice.id == invoice_id).one_or_none()
    if not invoice:
        abort(404)
    if (invoice.user_id != current_user.id 
            and current_user.user_type != UserType.admin):
        abort(401)
    return render_template("billing-invoice.html", invoice=invoice)

@billing.route("/billing/invoice/<int:invoice_id>", methods=["POST"])
@loginrequired
def invoice_POST(invoice_id):
    origin = cfg("meta.sr.ht", "api-origin", default=get_origin("meta.sr.ht"))
    headers = {
        "X-Forwarded-For": ", ".join(request.access_route),
        **encrypt_request_authorization(user=current_user),
    }
    r = requests.post(f"{origin}/query/invoice/{invoice_id}",
            headers=headers, data=request.form)
    filename = f"invoice_{invoice_id}.pdf"
    headers = [('Content-Disposition', f'attachment; filename="{filename}"')]
    return Response(r.content, mimetype="application/pdf", headers=headers)

metasrht/blueprints/keys.py
from datetime import datetime
from flask import Blueprint, render_template, request, redirect
from srht.graphql import exec_gql
from srht.oauth import current_user, loginrequired
from srht.validation import Validation

keys = Blueprint('keys', __name__)

@keys.route("/keys")
@loginrequired
def keys_GET():
    return render_template("keys.html", now=datetime.utcnow())

@keys.route("/keys/ssh-keys", methods=["POST"])
@loginrequired
def ssh_keys_POST():
    valid = Validation(request)
    resp = exec_gql("meta.sr.ht", """
    mutation CreateSSHKey($key: String!) {
        createSSHKey(key: $key) { id }
    }
    """, valid=valid, key=valid.source.get("ssh-key", ""))
    if not valid.ok:
        # The GraphQL parameter is called key, but we call it ssh-key to
        # disambiguate from PGP keys, which are configured on the same page.
        for err in valid.errors:
            if not err.field or err.field == "key":
                err.field = "ssh-key"
        return render_template("keys.html",
                now=datetime.utcnow(),
                ssh_key=valid.source.get("ssh-key", ""),
                **valid.kwargs), 400
    return redirect("/keys")

@keys.route("/keys/delete-ssh/<int:key_id>", methods=["POST"])
@loginrequired
def ssh_keys_delete(key_id):
    resp = exec_gql("meta.sr.ht", """
    mutation DeleteSSHKey($key: Int!) {
        deleteSSHKey(id: $key) { id }
    }
    """, key=key_id)
    return redirect("/keys")

@keys.route("/keys/pgp-keys", methods=["POST"])
@loginrequired
def pgp_keys_POST():
    valid = Validation(request)
    resp = exec_gql("meta.sr.ht", """
    mutation CreatePGPKey($key: String!) {
        createPGPKey(key: $key) { id }
    }
    """, valid=valid, key=valid.source.get("pgp-key", ""))
    if not valid.ok:
        # The GraphQL parameter is called key, but we call it pgp-key to
        # disambiguate from SSH keys, which are configured on the same page.
        for err in valid.errors:
            if not err.field or err.field == "key":
                err.field = "pgp-key"
        return render_template("keys.html",
                now=datetime.utcnow(),
                pgp_key=valid.source.get("pgp-key", ""),
                **valid.kwargs), 400
    return redirect("/keys")

@keys.route("/keys/delete-pgp/<int:key_id>", methods=["POST"])
@loginrequired
def pgp_keys_delete(key_id):
    # TODO: Move this logic into GQL
    if key_id == current_user.pgp_key_id:
        return render_template("keys.html",
                now=datetime.utcnow(),
                tried_to_delete_key_in_use=True), 400
    resp = exec_gql("meta.sr.ht", """
    mutation DeletePGPKey($key: Int!) {
        deletePGPKey(id: $key) { id }
    }
    """, key=key_id)
    return redirect("/keys")

metasrht/blueprints/profile.py
from flask import Blueprint, Response, render_template, request, abort
from flask import redirect, url_for
from metasrht.types import User, UserAuthFactor, FactorType
from srht.config import cfg
from srht.flask import session
from srht.database import db
from srht.oauth import current_user, loginrequired, login_user, logout_user
from srht.graphql import exec_gql
from srht.validation import Validation

profile = Blueprint('profile', __name__)

site_name = cfg("sr.ht", "site-name")

@profile.route("/~<username>.keys")
def user_keys_GET(username):
    user = User.query.filter(User.username == username).one_or_none()
    if not user:
        abort(404)
    resp = Response("\n".join(k.key.strip() for k in user.ssh_keys) + "\n")
    resp.headers["Content-Type"] = "text/plain"
    return resp

@profile.route("/~<username>.pgp")
def user_pgp_keys_GET(username):
    user = User.query.filter(User.username == username).one_or_none()
    if not user:
        abort(404)
    resp = Response("\n".join(k.key.strip() for k in user.pgp_keys) + "\n")
    resp.headers["Content-Type"] = "text/plain"
    return resp

@profile.route("/profile")
@loginrequired
def profile_GET():
    notice = session.pop("notice", None)
    return render_template("profile.html", notice=notice)

@profile.route("/profile", methods=["POST"])
@loginrequired
def profile_POST():
    valid = Validation(request)
    valid.require("email", friendly_name="Email")
    if not valid.ok:
        return render_template("profile.html", **valid.kwargs), 400
    rewrite = lambda value: None if value == "" else value
    input = {
        key: rewrite(valid.source[key]) for key in [
            "email", "url", "location", "bio",
        ] if valid.source.get(key) is not None
    }
    resp = exec_gql("meta.sr.ht", """
        mutation UpdateProfile($input: UserInput!) {
            updateUser(input: $input) { id, email }
        }
    """, valid=valid, input=input)
    if not valid.ok:
        return render_template("profile.html", **valid.kwargs), 400
    if "email" in valid.source and valid.source["email"] != resp["updateUser"]["email"]:
        session["notice"] = "An email has been sent to your new address. Check your inbox to complete the change."
    user = User.query.filter(User.id == resp["updateUser"]["id"]).one()
    login_user(user, set_cookie=True)
    return redirect(url_for(".profile_GET"))

@profile.route("/profile/delete")
@loginrequired
def profile_delete_GET():
    print(session.get("session_login"))
    if not session.get("session_login"):
        logout_user()
        session["login_context"] = "You must re-authenticate before deleting your account."
        return redirect(url_for("auth.login_GET",
                return_to=url_for("profile.profile_delete_POST")))
    return render_template("profile-delete.html")

@profile.route("/profile/delete", methods=["POST"])
@loginrequired
def profile_delete_POST():
    if not session.get("session_login"):
        logout_user()
        session["login_context"] = "You must re-authenticate before deleting your account."
        return redirect(url_for("auth.login_GET",
                return_to=url_for("profile.profile_delete_POST")))
    valid = Validation(request)
    confirm = valid.require("confirm")
    valid.expect(confirm == "on", "You must confirm you really want to delete this account.")
    reserve = valid.optional("reserve-username")
    reserve = reserve == "on"
    if not valid.ok:
        return render_template("profile-delete.html", **valid.kwargs)

    r = exec_gql("meta.sr.ht", """
    mutation DeleteUser($reserve: Boolean!) {
        deleteUser(reserve: $reserve)
    }
    """, reserve=reserve)

    logout_user()
    return redirect(url_for(".profile_deleted_GET"))

@profile.route("/profile/deleted")
def profile_deleted_GET():
    return render_template("profile-deleted.html")

metasrht/templates/billing-initial.html
{% extends "layout.html" %}
{% block title %}
<title>Choose a plan - {{cfg("sr.ht", "site-name")}}</title>
{% endblock %}
{% block content %}
<div class="row">
  <div class="col-md-12">
    <h3>
      Choose a plan
    </h3>
  </div>
</div>
<div class="row">
  <div class="col-md-12">
    <p>
      On {{cfg("sr.ht", "site-name")}}, all plans have access to the same
      features and in the same quantity. You should pick the plan which best
      matches your financial needs and best represents the level of investment
      you have in {{cfg("sr.ht", "site-name")}}. If you require financial aid
      to use {{cfg("sr.ht", "site-name")}}, please
      <a href="mailto:{{cfg("sr.ht", "owner-email")}}">send us an email</a>
      explaining your circumstances and we'll do our best to accommodate your
      needs.
    </p>
    <div class="alert alert-danger">
      <strong>Notice</strong>: {{cfg("sr.ht", "site-name")}} is currently
      considered at an alpha stage of development, and the quality of the
      service may reflect that. However, the service is reliable, stable,
      secure, and mostly complete at this stage of development. To learn
      exactly what the alpha entails,
      <a
        href="https://sourcehut.org/alpha-details/"
        rel="noopener"
        target="_blank"
      >consult this document</a>.
      During the alpha, payment is encouraged, but optional, for most features.
      <a
        href="{{url_for("profile.profile_GET")}}"
      >Continue without payment {{icon('caret-right')}}</a>.
    </div>
  </div>
</div>
<div class="row event-list" style="text-align: center">
  <div class="col-md-4">
    <form class="event" method="POST">
      {{csrf_token()}}
      <h3>Amateur Hackers</h3>
      <p>Includes access to all features.</p>
      <div style="margin-bottom: 1rem">
        <big>$2/month</big> or <big>$20/year</big>
      </div>
      <input type="hidden" name="amount" value="200" />
      <input type="hidden" name="plan" value="Amateur Hacker" />
      <button type="submit" class="btn btn-block btn-primary">
        Continue {{icon("caret-right")}}
      </button>
    </form>
  </div>
  <div class="col-md-4">
    <form class="event" method="POST">
      {{csrf_token()}}
      <h3>Typical Hackers</h3>
      <p>Includes access to all features.</p>
      <div class="text-center" style="margin-bottom: 1rem">
        <big>$5/month</big> or <big>$50/year</big>
      </div>
      <input type="hidden" name="amount" value="500" />
      <input type="hidden" name="plan" value="Typical Hacker" />
      <button type="submit" class="btn btn-block btn-primary">
        Continue {{icon("caret-right")}}
      </button>
    </form>
  </div>
  <div class="col-md-4">
    <form class="event" method="POST">
      {{csrf_token()}}
      <h3>Professional Hackers</h3>
      <p>Includes access to all features.</p>
      <div class="text-center" style="margin-bottom: 1rem">
        <big>$10/month</big> or <big>$100/year</big>
      </div>
      <input type="hidden" name="amount" value="1000" />
      <input type="hidden" name="plan" value="Professional Hacker" />
      <button type="submit" class="btn btn-block btn-primary">
        Continue {{icon("caret-right")}}
      </button>
    </form>
  </div>
</div>
<div class="row">
  <div class="col-md-12">
    <p class="text-muted text-center">
      <small>All prices are shown in US dollars.</small>
    </p>
    <div class="alert alert-warning">
      <strong>Notice</strong>: Continuing to the next page will execute
      non-free JavaScript from our payment processor,
      <a
        href="https://stripe.com/"
        target="_blank"
        rel="nofollow noopener"
      >Stripe</a>. If you are uncomfortable with this, please
      <a href="mailto:{{cfg('sr.ht', 'owner-email')}}">reach out to us</a> to
      discuss other options. For more information, consult our
      <a
        href="https://man.sr.ht/privacy.md"
        target="_blank"
        rel="noopener"
      >privacy policy</a>.
    </div>
    <p>
      You can cancel or change your plan at any time. Any questions?  Review our
      <a href="https://man.sr.ht/billing-faq.md">billing &amp; payments FAQ</a>.
    </p>
  </div>
</div>
<div class="row" style="margin-top: 3rem">
  <div class="col-md-12">
    <h3>Other ways to use {{cfg("sr.ht", "site-name")}}</h3>
  </div>
</div>
<div class="row event-list">
  <div class="col-md-4">
    <div class="event">
      <h3>Contributors</h3>
      <p>
        Just here to contribute bug reports, patches, and so on, to existing
        projects? You don't need to have a paid account for that.
      </p>
      <a
        class="btn btn-info btn-block"
        href="{{cfg("meta.sr.ht::settings", "onboarding-redirect")}}"
      >Continue {{icon("caret-right")}}</a>
    </div>
  </div>
  <div class="col-md-4">
    <div class="event">
      <h3>Earn free service</h3>
      <p>
        {{cfg("sr.ht", "site-name")}} is itself an
        <a
          href="https://sr.ht/~sircmpwn/sourcehut"
        >open-source project</a>. Users who contribute patches to the upstream
        project are eligible for free service.
      </p>
      <a
        class="btn btn-info btn-block"
        href="https://man.sr.ht/billing-faq.md#earning-service-credits-for-contributing-to-srht"
        target="_blank"
      >Learn more {{icon("caret-right")}}</a>
    </div>
  </div>
  <div class="col-md-4">
    <div class="event">
      <h3>Install it yourself</h3>
      <p>
        {{cfg("sr.ht", "site-name")}} is 100% free and open source software, and
        you can run it on your own servers free of charge if you prefer to host
        it yourself.
      </p>
      <a class="btn btn-info btn-block" href="https://man.sr.ht/installation.md">
        Read the docs {{icon("caret-right")}}
      </a>
    </div>
  </div>
</div>
{% endblock %}

metasrht/templates/billing.html
{% extends "meta.html" %}
{% block title %}
<title>Billing - {{cfg("sr.ht", "site-name")}} meta</title>
{% endblock %}
{% block content %}
<div class="row">
  <div class="col-md-12">
    <h3>Billing Information</h3>
    {% if message %}
    <div class="alert alert-info">{{message}}</div>
    {% endif %}

    {% if current_user.user_type == UserType.active_non_paying %}

    <div class="alert alert-info">
      You are currently using an <strong>unpaid</strong>
      {{cfg("sr.ht", "site-name")}} account. Some site features may be
      unavailable to your account.
    </div>

    {% elif current_user.user_type == UserType.active_free %}

    <div class="alert alert-info">
      Your account is <strong>exempt</strong> from billing. All features are
      available to you free of charge. You may choose to set up billing
      if you wish to support the site.
    </div>

    {% elif current_user.user_type == UserType.active_paying %}

    {% if current_user.payment_cents == 0 %}

    <div class="alert alert-warning">
      Your paid service has been cancelled. At the end of your current term,
      {{current_user.payment_due | date}}, your account will be downgraded to a
      non-paying account.
    </div>

    {% else %}

    <div class="alert alert-success">
      {% if invoices %}
      Your account is <strong>paid</strong> and up-to-date, and your last
      payment of {{"${:.2f}".format(invoices[0].cents/100)}}
      was made {{invoices[0].created | date}}. Your current
      {{current_user.payment_interval.value}} payment is
      {{"${:.2f}".format(current_user.payment_cents/100
        if current_user.payment_interval.value == "monthly"
        else current_user.payment_cents*10/100)}} and will be billed
      {{invoices[0].valid_thru | date}}.
      {% else %}
      Your account is <strong>paid</strong> and up-to-date. Your
      current {{current_user.payment_interval.value}} payment is
      {{"${:.2f}".format(current_user.payment_cents/100
        if current_user.payment_interval.value == "monthly"
        else current_user.payment_cents*10/100)}}.
      {% endif %}
    </div>

    {% endif %}

    {% elif current_user.user_type == UserType.active_delinquent %}

    <div class="alert alert-danger">
      <strong>Notice</strong>: Your payment is past due. Please check that your
      payment information is correct or your service may be impacted.
    </div>

    {% elif current_user.user_type == UserType.admin %}

    <div class="alert alert-info">
      Admins are exempt from billing.
    </div>

    {% endif %}

    <div style="margin-bottom: 1rem">
      <div class="progress">
        <div class="progress-bar"
          role="progressbar"
          style="width: {{paid_pct}}%;"
          aria-valuenow="{{paid_pct}}"
          aria-valuemin="0" aria-valuemax="100"
        >{{paid_pct}}% paid</div>
        <div
          class="goal"
          style="left: 13.37%"
          title="Presented without comment"
        >13.37%</div>
        <div class="progress-bar total">of {{total_users}} registered users</div>
      </div>
      <small class="text-muted pull-right">
        Current number of paid accounts on {{cfg("sr.ht", "site-name")}}
      </small>
    </div>
  </div>
</div>
{% if current_user.user_type == UserType.active_paying
  and current_user.payment_cents != 0 %}
<div class="row" style="margin-bottom: 1rem">
  <div class="col-md-3 offset-md-6">
    <a
      href="{{url_for("billing.billing_initial_GET")}}"
      class="btn btn-default btn-block"
    >Change your plan {{icon('caret-right')}}</a>
  </div>
  <div class="col-md-3">
    <form method="POST" action="{{url_for("billing.cancel_POST")}}">
      {{csrf_token()}}
      <button class="btn btn-danger btn-block">
        Cancel your plan {{icon('caret-right')}}
      </button>
    </form>
  </div>
</div>
{% elif current_user.user_type == UserType.active_delinquent %}
<div class="row" style="margin-bottom: 1rem">
  <div class="col-md-3 offset-md-3">
    <a
      href="{{url_for("billing.billing_initial_GET")}}"
      class="btn btn-default btn-block"
    >Change your plan {{icon('caret-right')}}</a>
  </div>
  <div class="col-md-3">
    <form method="POST" action="{{url_for("billing.cancel_POST")}}">
      {{csrf_token()}}
      <button class="btn btn-danger btn-block">
        Cancel your plan {{icon('caret-right')}}
      </button>
    </form>
  </div>
  <div class="col-md-3">
    <a
      href="{{url_for("billing.new_payment_GET")}}"
      class="btn btn-primary btn-block"
    >Add payment method {{icon('caret-right')}}</a>
  </div>
</div>
{% elif current_user.user_type == UserType.active_paying
  and current_user.payment_cents == 0 %}
<div class="row" style="margin-bottom: 1rem">
  <div class="col-md-3 offset-md-9">
    <a
      href="{{url_for("billing.billing_initial_GET")}}"
      class="btn btn-primary btn-block"
    >Renew your account {{icon('caret-right')}}</a>
  </div>
</div>
{% elif current_user.user_type in [
  UserType.active_non_paying,
  UserType.active_free
] %}
<div class="row" style="margin-bottom: 1rem">
  <div class="col-md-3 offset-md-9">
    <a
      href="{{url_for("billing.billing_initial_GET")}}"
      class="btn btn-primary btn-block"
    >Set up billing {{icon('caret-right')}}</a>
  </div>
</div>
{% endif %}
<div class="row">
  <div class="col-md-6">
    {% if current_user.user_type in [
      UserType.active_paying,
      UserType.active_delinquent
    ] %}
    <h3>Payment methods</h3>
    <div class="event-list">
      {% for source in customer.sources %}
      <div class="event row">
        <div class="col-md-8">
          {{source.brand}} ending in {{source.last4}}
          <br />
          <span class="text-muted">
            {% if source.address_zip %}
            Post code {{source.address_zip}}.
            {% endif %}
            Expires {{source.exp_month}}/{{source.exp_year}}.
          </span>
        </div>
        <div class="col-md-4">
          <div style="text-align: right">
            {% if source.stripe_id == customer.default_source %}
            {{icon('check', cls="text-success")}} Default
            {% else %}
            <form style="margin: 0;" method="POST"
              action="{{url_for("billing.payment_source_remove",
                source_id=source.id)}}">
              {{csrf_token()}}
              <button class="btn btn-link">
                Remove {{icon('times')}}
              </button>
            </form>
            <form method="POST"
              action="{{url_for("billing.payment_source_make_default",
                source_id=source.id)}}">
              {{csrf_token()}}
              <button class="btn btn-link">
                Make default {{icon('caret-right')}}
              </button>
            </form>
            {% endif %}
          </div>
        </div>
      </div>
      {% endfor %}
    </div>
    <a
      href="{{url_for("billing.new_payment_GET")}}"
      class="btn btn-primary pull-right"
    >New payment method {{icon('caret-right')}}</a>
    {% endif %}
  </div>
  {% if len(invoices) != 0 %}
  <div class="col-md-6">
    <h3>Invoices</h3>
    <div class="event-list">
      {% for invoice in invoices %}
      <div class="event invoice">
        <h4>
          <small class="text-success" style="margin-left: 0">
            {{icon('check')}}
          </small>
          ${{"{:.2f}".format(invoice.cents/100)}}
          <small>
            with {{invoice.source}}
          </small>
          <small>
            <a
              class="pull-right"
              href="{{url_for("billing.invoice_GET", invoice_id=invoice.id)}}"
            >Export as PDF</a>
          </small>
        </h4>
        <p>
          Paid {{invoice.created | date}}<br />
          Valid for service until {{invoice.valid_thru | date}}
          {% if invoice.comment %}
          <br />
          {{invoice.comment}}
          {% endif %}
        </p>
      </div>
      {% endfor %}
    </div>
  </div>
  {% endif %}
</div>
{% endblock %}

metasrht/templates/oauth-oob.html
{% extends "layout.html" %}
{% block title %}
<title>OAuth Callback - {{cfg("sr.ht", "site-name")}} meta</title>
{% endblock %}
{% block content %}
<div class="row">
  <section class="col-md-6">
    <h3>Sign In</h3>
    <p>
      Please copy and paste the following into the application.
    </p>
    <pre>{{ exchange_token }}</pre>
  </section>
</div>
{% endblock %}